version: '3.9'

services:
  db:
    image: postgres:15
    container_name: metrics_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: metrics
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    command: ["postgres", "-c", "fsync=off"]

  migrate:
    image: postgres:15
    depends_on:
      - db
    entrypoint: ["bash", "-c", "sleep 3 && psql postgresql://admin:admin@db:5432/metrics -f /migrations/migrations.sql"]
    volumes:
      - ./server/pkg/db/migrations.sql:/migrations/migrations.sql

  server:
    build: ./server
    container_name: go_grpc_server
    depends_on:
      - db
      - migrate
    ports:
      - "50051:50051"

  dashboard:
    build: ./dashboard
    container_name: dashboard_app
    ports:
      - "8080:8080"

volumes:
  db_data: